# Data Preprocessing Template

## Importing the libraries

In [18]:
# function for testing variables and functions
def test_comp(variable):
    print(variable)
    try:
        for i in variable:
            print(i)
    except TypeError:
        print("Not iterable")

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [67]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values

In [68]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:,1:3] = imputer.transform(X[:, 1:3])

## Encoding categorical data
### One Hot Encoding

In [30]:
# One hot encoding in a method of converting categorical data to prepare it for better predictions
# Can be related to Factors & Levels in R
# transforming countries into numerical mapping,
# for eg France = 0, Spain = 1, Germany = 2

In [71]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])], remainder='passthrough')

# The "remainder" parameter
#### If not specified, the remaining columns (columns which do not under-go transformation) will be dropped from the transformed array.
#### If set to 'passthrough', all remaining columns that were not specified in transformers will be automatically passed through. This subset of columns is concatenated with the output of the transformers.


In [70]:
# Here the transformer encodes France = 1 0 0, Spain = 0 1 0, Germany = 0 0 1
# TODO: Trying to use OneHotEncoder on DSLABS:Murders and trying to revomer remainder parameter
X = np.array(ct.fit_transform(X))
print(X)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [63]:
# Encoding the dependent variable
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
# No need of a NumPy Array here as the dependent variable is a single column vector and not a matrix of features and labels like the independent variable X
Y = le.fit_transform(Y)

In [72]:
import sentry_sdk
sentry_sdk.init(
    dsn="https://6c6bf97926754facbf3ec9d7415898ba@o1395686.ingest.sentry.io/6718734",

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    traces_sample_rate=1.0
)
division_error = 1/0

ZeroDivisionError: division by zero